// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Rdp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RdpBridge.Protocol {

  /// <summary>Holder for reflection information generated from Rdp.proto</summary>
  public static partial class RdpReflection {

    #region Descriptor
    /// <summary>File descriptor for Rdp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RdpReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CglSZHAucHJvdG8SA1JkcCL5AgoKUmRwTWVzc2FnZRIvCgpkaXNjb25uZWN0",
            "GAEgASgLMhkuUmRwLlJkcERpc2Nvbm5lY3RNZXNzYWdlSAASPQoRdmVyaWZ5",
            "Q2VydGlmaWNhdGUYAiABKAsyIC5SZHAuUmRwVmVyaWZ5Q2VydGlmaWNhdGVN",
            "ZXNzYWdlSAASSQoXdmVyaWZ5Q2VydGlmaWNhdGVSZXN1bHQYAyABKAsyJi5S",
            "ZHAuUmRwVmVyaWZ5Q2VydGlmaWNhdGVSZXN1bHRNZXNzYWdlSAASMwoMYXV0",
            "aGVudGljYXRlGAQgASgLMhsuUmRwLlJkcEF1dGhlbnRpY2F0ZU1lc3NhZ2VI",
            "ABI/ChJhdXRoZW50aWNhdGVSZXN1bHQYBSABKAsyIS5SZHAuUmRwQXV0aGVu",
            "dGljYXRlUmVzdWx0TWVzc2FnZUgAEi8KCnNlc3Npb25FbmQYBiABKAsyGS5S",
            "ZHAuUmRwU2Vzc2lvbkVuZE1lc3NhZ2VIAEIJCgdtZXNzYWdlIhYKFFJkcERp",
            "c2Nvbm5lY3RNZXNzYWdlIkwKFlJkcEF1dGhlbnRpY2F0ZU1lc3NhZ2USEAoI",
            "dXNlcm5hbWUYASABKAkSEAoIcGFzc3dvcmQYAiABKAkSDgoGZG9tYWluGAMg",
            "ASgJImsKHFJkcEF1dGhlbnRpY2F0ZVJlc3VsdE1lc3NhZ2USEAoIdXNlcm5h",
            "bWUYASABKAkSEAoIcGFzc3dvcmQYAiABKAkSDgoGZG9tYWluGAMgASgJEhcK",
            "D3Bhc3N3b3JkRW50ZXJlZBgEIAEoCCJjChtSZHBWZXJpZnlDZXJ0aWZpY2F0",
            "ZU1lc3NhZ2USFQoNeDUwOUNlcnRCeXRlcxgBIAEoDBIQCghob3N0bmFtZRgC",
            "IAEoCRIMCgRwb3J0GAMgASgNEg0KBWZsYWdzGAQgASgNItQBCiFSZHBWZXJp",
            "ZnlDZXJ0aWZpY2F0ZVJlc3VsdE1lc3NhZ2USUQoGcmVzdWx0GAEgASgOMkEu",
            "UmRwLlJkcFZlcmlmeUNlcnRpZmljYXRlUmVzdWx0TWVzc2FnZS5SZHBWZXJp",
            "ZnlDZXJ0aWZpY2F0ZVJlc3VsdCJcChpSZHBWZXJpZnlDZXJ0aWZpY2F0ZVJl",
            "c3VsdBIOCgpOb3RUcnVzdGVkEAASFgoSUGVybWVuYW50bHlUcnVzdGVkEAES",
            "FgoSVGVtcG9yYXJpbHlUcnVzdGVkEAIiFgoUUmRwU2Vzc2lvbkVuZE1lc3Nh",
            "Z2VCFaoCElJkcEJyaWRnZS5Qcm90b2NvbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::RdpBridge.Protocol.RdpMessage), global::RdpBridge.Protocol.RdpMessage.Parser, new[]{ "Disconnect", "VerifyCertificate", "VerifyCertificateResult", "Authenticate", "AuthenticateResult", "SessionEnd" }, new[]{ "Message" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::RdpBridge.Protocol.RdpDisconnectMessage), global::RdpBridge.Protocol.RdpDisconnectMessage.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::RdpBridge.Protocol.RdpAuthenticateMessage), global::RdpBridge.Protocol.RdpAuthenticateMessage.Parser, new[]{ "Username", "Password", "Domain" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::RdpBridge.Protocol.RdpAuthenticateResultMessage), global::RdpBridge.Protocol.RdpAuthenticateResultMessage.Parser, new[]{ "Username", "Password", "Domain", "PasswordEntered" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::RdpBridge.Protocol.RdpVerifyCertificateMessage), global::RdpBridge.Protocol.RdpVerifyCertificateMessage.Parser, new[]{ "X509CertBytes", "Hostname", "Port", "Flags" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage), global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage.Parser, new[]{ "Result" }, null, new[]{ typeof(global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage.Types.RdpVerifyCertificateResult) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::RdpBridge.Protocol.RdpSessionEndMessage), global::RdpBridge.Protocol.RdpSessionEndMessage.Parser, null, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RdpMessage : pb::IMessage<RdpMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RdpMessage> _parser = new pb::MessageParser<RdpMessage>(() => new RdpMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RdpMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RdpBridge.Protocol.RdpReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpMessage(RdpMessage other) : this() {
      switch (other.MessageCase) {
        case MessageOneofCase.Disconnect:
          Disconnect = other.Disconnect.Clone();
          break;
        case MessageOneofCase.VerifyCertificate:
          VerifyCertificate = other.VerifyCertificate.Clone();
          break;
        case MessageOneofCase.VerifyCertificateResult:
          VerifyCertificateResult = other.VerifyCertificateResult.Clone();
          break;
        case MessageOneofCase.Authenticate:
          Authenticate = other.Authenticate.Clone();
          break;
        case MessageOneofCase.AuthenticateResult:
          AuthenticateResult = other.AuthenticateResult.Clone();
          break;
        case MessageOneofCase.SessionEnd:
          SessionEnd = other.SessionEnd.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpMessage Clone() {
      return new RdpMessage(this);
    }

    /// <summary>Field number for the "disconnect" field.</summary>
    public const int DisconnectFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::RdpBridge.Protocol.RdpDisconnectMessage Disconnect {
      get { return messageCase_ == MessageOneofCase.Disconnect ? (global::RdpBridge.Protocol.RdpDisconnectMessage) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.Disconnect;
      }
    }

    /// <summary>Field number for the "verifyCertificate" field.</summary>
    public const int VerifyCertificateFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::RdpBridge.Protocol.RdpVerifyCertificateMessage VerifyCertificate {
      get { return messageCase_ == MessageOneofCase.VerifyCertificate ? (global::RdpBridge.Protocol.RdpVerifyCertificateMessage) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.VerifyCertificate;
      }
    }

    /// <summary>Field number for the "verifyCertificateResult" field.</summary>
    public const int VerifyCertificateResultFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage VerifyCertificateResult {
      get { return messageCase_ == MessageOneofCase.VerifyCertificateResult ? (global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.VerifyCertificateResult;
      }
    }

    /// <summary>Field number for the "authenticate" field.</summary>
    public const int AuthenticateFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::RdpBridge.Protocol.RdpAuthenticateMessage Authenticate {
      get { return messageCase_ == MessageOneofCase.Authenticate ? (global::RdpBridge.Protocol.RdpAuthenticateMessage) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.Authenticate;
      }
    }

    /// <summary>Field number for the "authenticateResult" field.</summary>
    public const int AuthenticateResultFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::RdpBridge.Protocol.RdpAuthenticateResultMessage AuthenticateResult {
      get { return messageCase_ == MessageOneofCase.AuthenticateResult ? (global::RdpBridge.Protocol.RdpAuthenticateResultMessage) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.AuthenticateResult;
      }
    }

    /// <summary>Field number for the "sessionEnd" field.</summary>
    public const int SessionEndFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::RdpBridge.Protocol.RdpSessionEndMessage SessionEnd {
      get { return messageCase_ == MessageOneofCase.SessionEnd ? (global::RdpBridge.Protocol.RdpSessionEndMessage) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.SessionEnd;
      }
    }

    private object message_;
    /// <summary>Enum of possible cases for the "message" oneof.</summary>
    public enum MessageOneofCase {
      None = 0,
      Disconnect = 1,
      VerifyCertificate = 2,
      VerifyCertificateResult = 3,
      Authenticate = 4,
      AuthenticateResult = 5,
      SessionEnd = 6,
    }
    private MessageOneofCase messageCase_ = MessageOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageOneofCase MessageCase {
      get { return messageCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMessage() {
      messageCase_ = MessageOneofCase.None;
      message_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RdpMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RdpMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Disconnect, other.Disconnect)) return false;
      if (!object.Equals(VerifyCertificate, other.VerifyCertificate)) return false;
      if (!object.Equals(VerifyCertificateResult, other.VerifyCertificateResult)) return false;
      if (!object.Equals(Authenticate, other.Authenticate)) return false;
      if (!object.Equals(AuthenticateResult, other.AuthenticateResult)) return false;
      if (!object.Equals(SessionEnd, other.SessionEnd)) return false;
      if (MessageCase != other.MessageCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (messageCase_ == MessageOneofCase.Disconnect) hash ^= Disconnect.GetHashCode();
      if (messageCase_ == MessageOneofCase.VerifyCertificate) hash ^= VerifyCertificate.GetHashCode();
      if (messageCase_ == MessageOneofCase.VerifyCertificateResult) hash ^= VerifyCertificateResult.GetHashCode();
      if (messageCase_ == MessageOneofCase.Authenticate) hash ^= Authenticate.GetHashCode();
      if (messageCase_ == MessageOneofCase.AuthenticateResult) hash ^= AuthenticateResult.GetHashCode();
      if (messageCase_ == MessageOneofCase.SessionEnd) hash ^= SessionEnd.GetHashCode();
      hash ^= (int) messageCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (messageCase_ == MessageOneofCase.Disconnect) {
        output.WriteRawTag(10);
        output.WriteMessage(Disconnect);
      }
      if (messageCase_ == MessageOneofCase.VerifyCertificate) {
        output.WriteRawTag(18);
        output.WriteMessage(VerifyCertificate);
      }
      if (messageCase_ == MessageOneofCase.VerifyCertificateResult) {
        output.WriteRawTag(26);
        output.WriteMessage(VerifyCertificateResult);
      }
      if (messageCase_ == MessageOneofCase.Authenticate) {
        output.WriteRawTag(34);
        output.WriteMessage(Authenticate);
      }
      if (messageCase_ == MessageOneofCase.AuthenticateResult) {
        output.WriteRawTag(42);
        output.WriteMessage(AuthenticateResult);
      }
      if (messageCase_ == MessageOneofCase.SessionEnd) {
        output.WriteRawTag(50);
        output.WriteMessage(SessionEnd);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (messageCase_ == MessageOneofCase.Disconnect) {
        output.WriteRawTag(10);
        output.WriteMessage(Disconnect);
      }
      if (messageCase_ == MessageOneofCase.VerifyCertificate) {
        output.WriteRawTag(18);
        output.WriteMessage(VerifyCertificate);
      }
      if (messageCase_ == MessageOneofCase.VerifyCertificateResult) {
        output.WriteRawTag(26);
        output.WriteMessage(VerifyCertificateResult);
      }
      if (messageCase_ == MessageOneofCase.Authenticate) {
        output.WriteRawTag(34);
        output.WriteMessage(Authenticate);
      }
      if (messageCase_ == MessageOneofCase.AuthenticateResult) {
        output.WriteRawTag(42);
        output.WriteMessage(AuthenticateResult);
      }
      if (messageCase_ == MessageOneofCase.SessionEnd) {
        output.WriteRawTag(50);
        output.WriteMessage(SessionEnd);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (messageCase_ == MessageOneofCase.Disconnect) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Disconnect);
      }
      if (messageCase_ == MessageOneofCase.VerifyCertificate) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VerifyCertificate);
      }
      if (messageCase_ == MessageOneofCase.VerifyCertificateResult) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VerifyCertificateResult);
      }
      if (messageCase_ == MessageOneofCase.Authenticate) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Authenticate);
      }
      if (messageCase_ == MessageOneofCase.AuthenticateResult) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AuthenticateResult);
      }
      if (messageCase_ == MessageOneofCase.SessionEnd) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SessionEnd);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RdpMessage other) {
      if (other == null) {
        return;
      }
      switch (other.MessageCase) {
        case MessageOneofCase.Disconnect:
          if (Disconnect == null) {
            Disconnect = new global::RdpBridge.Protocol.RdpDisconnectMessage();
          }
          Disconnect.MergeFrom(other.Disconnect);
          break;
        case MessageOneofCase.VerifyCertificate:
          if (VerifyCertificate == null) {
            VerifyCertificate = new global::RdpBridge.Protocol.RdpVerifyCertificateMessage();
          }
          VerifyCertificate.MergeFrom(other.VerifyCertificate);
          break;
        case MessageOneofCase.VerifyCertificateResult:
          if (VerifyCertificateResult == null) {
            VerifyCertificateResult = new global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage();
          }
          VerifyCertificateResult.MergeFrom(other.VerifyCertificateResult);
          break;
        case MessageOneofCase.Authenticate:
          if (Authenticate == null) {
            Authenticate = new global::RdpBridge.Protocol.RdpAuthenticateMessage();
          }
          Authenticate.MergeFrom(other.Authenticate);
          break;
        case MessageOneofCase.AuthenticateResult:
          if (AuthenticateResult == null) {
            AuthenticateResult = new global::RdpBridge.Protocol.RdpAuthenticateResultMessage();
          }
          AuthenticateResult.MergeFrom(other.AuthenticateResult);
          break;
        case MessageOneofCase.SessionEnd:
          if (SessionEnd == null) {
            SessionEnd = new global::RdpBridge.Protocol.RdpSessionEndMessage();
          }
          SessionEnd.MergeFrom(other.SessionEnd);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::RdpBridge.Protocol.RdpDisconnectMessage subBuilder = new global::RdpBridge.Protocol.RdpDisconnectMessage();
            if (messageCase_ == MessageOneofCase.Disconnect) {
              subBuilder.MergeFrom(Disconnect);
            }
            input.ReadMessage(subBuilder);
            Disconnect = subBuilder;
            break;
          }
          case 18: {
            global::RdpBridge.Protocol.RdpVerifyCertificateMessage subBuilder = new global::RdpBridge.Protocol.RdpVerifyCertificateMessage();
            if (messageCase_ == MessageOneofCase.VerifyCertificate) {
              subBuilder.MergeFrom(VerifyCertificate);
            }
            input.ReadMessage(subBuilder);
            VerifyCertificate = subBuilder;
            break;
          }
          case 26: {
            global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage subBuilder = new global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage();
            if (messageCase_ == MessageOneofCase.VerifyCertificateResult) {
              subBuilder.MergeFrom(VerifyCertificateResult);
            }
            input.ReadMessage(subBuilder);
            VerifyCertificateResult = subBuilder;
            break;
          }
          case 34: {
            global::RdpBridge.Protocol.RdpAuthenticateMessage subBuilder = new global::RdpBridge.Protocol.RdpAuthenticateMessage();
            if (messageCase_ == MessageOneofCase.Authenticate) {
              subBuilder.MergeFrom(Authenticate);
            }
            input.ReadMessage(subBuilder);
            Authenticate = subBuilder;
            break;
          }
          case 42: {
            global::RdpBridge.Protocol.RdpAuthenticateResultMessage subBuilder = new global::RdpBridge.Protocol.RdpAuthenticateResultMessage();
            if (messageCase_ == MessageOneofCase.AuthenticateResult) {
              subBuilder.MergeFrom(AuthenticateResult);
            }
            input.ReadMessage(subBuilder);
            AuthenticateResult = subBuilder;
            break;
          }
          case 50: {
            global::RdpBridge.Protocol.RdpSessionEndMessage subBuilder = new global::RdpBridge.Protocol.RdpSessionEndMessage();
            if (messageCase_ == MessageOneofCase.SessionEnd) {
              subBuilder.MergeFrom(SessionEnd);
            }
            input.ReadMessage(subBuilder);
            SessionEnd = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::RdpBridge.Protocol.RdpDisconnectMessage subBuilder = new global::RdpBridge.Protocol.RdpDisconnectMessage();
            if (messageCase_ == MessageOneofCase.Disconnect) {
              subBuilder.MergeFrom(Disconnect);
            }
            input.ReadMessage(subBuilder);
            Disconnect = subBuilder;
            break;
          }
          case 18: {
            global::RdpBridge.Protocol.RdpVerifyCertificateMessage subBuilder = new global::RdpBridge.Protocol.RdpVerifyCertificateMessage();
            if (messageCase_ == MessageOneofCase.VerifyCertificate) {
              subBuilder.MergeFrom(VerifyCertificate);
            }
            input.ReadMessage(subBuilder);
            VerifyCertificate = subBuilder;
            break;
          }
          case 26: {
            global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage subBuilder = new global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage();
            if (messageCase_ == MessageOneofCase.VerifyCertificateResult) {
              subBuilder.MergeFrom(VerifyCertificateResult);
            }
            input.ReadMessage(subBuilder);
            VerifyCertificateResult = subBuilder;
            break;
          }
          case 34: {
            global::RdpBridge.Protocol.RdpAuthenticateMessage subBuilder = new global::RdpBridge.Protocol.RdpAuthenticateMessage();
            if (messageCase_ == MessageOneofCase.Authenticate) {
              subBuilder.MergeFrom(Authenticate);
            }
            input.ReadMessage(subBuilder);
            Authenticate = subBuilder;
            break;
          }
          case 42: {
            global::RdpBridge.Protocol.RdpAuthenticateResultMessage subBuilder = new global::RdpBridge.Protocol.RdpAuthenticateResultMessage();
            if (messageCase_ == MessageOneofCase.AuthenticateResult) {
              subBuilder.MergeFrom(AuthenticateResult);
            }
            input.ReadMessage(subBuilder);
            AuthenticateResult = subBuilder;
            break;
          }
          case 50: {
            global::RdpBridge.Protocol.RdpSessionEndMessage subBuilder = new global::RdpBridge.Protocol.RdpSessionEndMessage();
            if (messageCase_ == MessageOneofCase.SessionEnd) {
              subBuilder.MergeFrom(SessionEnd);
            }
            input.ReadMessage(subBuilder);
            SessionEnd = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RdpDisconnectMessage : pb::IMessage<RdpDisconnectMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RdpDisconnectMessage> _parser = new pb::MessageParser<RdpDisconnectMessage>(() => new RdpDisconnectMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RdpDisconnectMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RdpBridge.Protocol.RdpReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpDisconnectMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpDisconnectMessage(RdpDisconnectMessage other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpDisconnectMessage Clone() {
      return new RdpDisconnectMessage(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RdpDisconnectMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RdpDisconnectMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RdpDisconnectMessage other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class RdpAuthenticateMessage : pb::IMessage<RdpAuthenticateMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RdpAuthenticateMessage> _parser = new pb::MessageParser<RdpAuthenticateMessage>(() => new RdpAuthenticateMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RdpAuthenticateMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RdpBridge.Protocol.RdpReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpAuthenticateMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpAuthenticateMessage(RdpAuthenticateMessage other) : this() {
      username_ = other.username_;
      password_ = other.password_;
      domain_ = other.domain_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpAuthenticateMessage Clone() {
      return new RdpAuthenticateMessage(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "domain" field.</summary>
    public const int DomainFieldNumber = 3;
    private string domain_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Domain {
      get { return domain_; }
      set {
        domain_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RdpAuthenticateMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RdpAuthenticateMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      if (Domain != other.Domain) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (Domain.Length != 0) hash ^= Domain.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (Domain.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Domain);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (Domain.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Domain);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (Domain.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Domain);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RdpAuthenticateMessage other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.Domain.Length != 0) {
        Domain = other.Domain;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
          case 26: {
            Domain = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
          case 26: {
            Domain = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RdpAuthenticateResultMessage : pb::IMessage<RdpAuthenticateResultMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RdpAuthenticateResultMessage> _parser = new pb::MessageParser<RdpAuthenticateResultMessage>(() => new RdpAuthenticateResultMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RdpAuthenticateResultMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RdpBridge.Protocol.RdpReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpAuthenticateResultMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpAuthenticateResultMessage(RdpAuthenticateResultMessage other) : this() {
      username_ = other.username_;
      password_ = other.password_;
      domain_ = other.domain_;
      passwordEntered_ = other.passwordEntered_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpAuthenticateResultMessage Clone() {
      return new RdpAuthenticateResultMessage(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "domain" field.</summary>
    public const int DomainFieldNumber = 3;
    private string domain_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Domain {
      get { return domain_; }
      set {
        domain_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "passwordEntered" field.</summary>
    public const int PasswordEnteredFieldNumber = 4;
    private bool passwordEntered_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool PasswordEntered {
      get { return passwordEntered_; }
      set {
        passwordEntered_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RdpAuthenticateResultMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RdpAuthenticateResultMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      if (Domain != other.Domain) return false;
      if (PasswordEntered != other.PasswordEntered) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (Domain.Length != 0) hash ^= Domain.GetHashCode();
      if (PasswordEntered != false) hash ^= PasswordEntered.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (Domain.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Domain);
      }
      if (PasswordEntered != false) {
        output.WriteRawTag(32);
        output.WriteBool(PasswordEntered);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (Domain.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Domain);
      }
      if (PasswordEntered != false) {
        output.WriteRawTag(32);
        output.WriteBool(PasswordEntered);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (Domain.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Domain);
      }
      if (PasswordEntered != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RdpAuthenticateResultMessage other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.Domain.Length != 0) {
        Domain = other.Domain;
      }
      if (other.PasswordEntered != false) {
        PasswordEntered = other.PasswordEntered;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
          case 26: {
            Domain = input.ReadString();
            break;
          }
          case 32: {
            PasswordEntered = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
          case 26: {
            Domain = input.ReadString();
            break;
          }
          case 32: {
            PasswordEntered = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RdpVerifyCertificateMessage : pb::IMessage<RdpVerifyCertificateMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RdpVerifyCertificateMessage> _parser = new pb::MessageParser<RdpVerifyCertificateMessage>(() => new RdpVerifyCertificateMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RdpVerifyCertificateMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RdpBridge.Protocol.RdpReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpVerifyCertificateMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpVerifyCertificateMessage(RdpVerifyCertificateMessage other) : this() {
      x509CertBytes_ = other.x509CertBytes_;
      hostname_ = other.hostname_;
      port_ = other.port_;
      flags_ = other.flags_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpVerifyCertificateMessage Clone() {
      return new RdpVerifyCertificateMessage(this);
    }

    /// <summary>Field number for the "x509CertBytes" field.</summary>
    public const int X509CertBytesFieldNumber = 1;
    private pb::ByteString x509CertBytes_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString X509CertBytes {
      get { return x509CertBytes_; }
      set {
        x509CertBytes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "hostname" field.</summary>
    public const int HostnameFieldNumber = 2;
    private string hostname_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Hostname {
      get { return hostname_; }
      set {
        hostname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "port" field.</summary>
    public const int PortFieldNumber = 3;
    private uint port_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Port {
      get { return port_; }
      set {
        port_ = value;
      }
    }

    /// <summary>Field number for the "flags" field.</summary>
    public const int FlagsFieldNumber = 4;
    private uint flags_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Flags {
      get { return flags_; }
      set {
        flags_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RdpVerifyCertificateMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RdpVerifyCertificateMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (X509CertBytes != other.X509CertBytes) return false;
      if (Hostname != other.Hostname) return false;
      if (Port != other.Port) return false;
      if (Flags != other.Flags) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (X509CertBytes.Length != 0) hash ^= X509CertBytes.GetHashCode();
      if (Hostname.Length != 0) hash ^= Hostname.GetHashCode();
      if (Port != 0) hash ^= Port.GetHashCode();
      if (Flags != 0) hash ^= Flags.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (X509CertBytes.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(X509CertBytes);
      }
      if (Hostname.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Hostname);
      }
      if (Port != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Port);
      }
      if (Flags != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Flags);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (X509CertBytes.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(X509CertBytes);
      }
      if (Hostname.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Hostname);
      }
      if (Port != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Port);
      }
      if (Flags != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Flags);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (X509CertBytes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(X509CertBytes);
      }
      if (Hostname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Hostname);
      }
      if (Port != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Port);
      }
      if (Flags != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Flags);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RdpVerifyCertificateMessage other) {
      if (other == null) {
        return;
      }
      if (other.X509CertBytes.Length != 0) {
        X509CertBytes = other.X509CertBytes;
      }
      if (other.Hostname.Length != 0) {
        Hostname = other.Hostname;
      }
      if (other.Port != 0) {
        Port = other.Port;
      }
      if (other.Flags != 0) {
        Flags = other.Flags;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            X509CertBytes = input.ReadBytes();
            break;
          }
          case 18: {
            Hostname = input.ReadString();
            break;
          }
          case 24: {
            Port = input.ReadUInt32();
            break;
          }
          case 32: {
            Flags = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            X509CertBytes = input.ReadBytes();
            break;
          }
          case 18: {
            Hostname = input.ReadString();
            break;
          }
          case 24: {
            Port = input.ReadUInt32();
            break;
          }
          case 32: {
            Flags = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RdpVerifyCertificateResultMessage : pb::IMessage<RdpVerifyCertificateResultMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RdpVerifyCertificateResultMessage> _parser = new pb::MessageParser<RdpVerifyCertificateResultMessage>(() => new RdpVerifyCertificateResultMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RdpVerifyCertificateResultMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RdpBridge.Protocol.RdpReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpVerifyCertificateResultMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpVerifyCertificateResultMessage(RdpVerifyCertificateResultMessage other) : this() {
      result_ = other.result_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpVerifyCertificateResultMessage Clone() {
      return new RdpVerifyCertificateResultMessage(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage.Types.RdpVerifyCertificateResult result_ = global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage.Types.RdpVerifyCertificateResult.NotTrusted;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage.Types.RdpVerifyCertificateResult Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RdpVerifyCertificateResultMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RdpVerifyCertificateResultMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage.Types.RdpVerifyCertificateResult.NotTrusted) hash ^= Result.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Result != global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage.Types.RdpVerifyCertificateResult.NotTrusted) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Result != global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage.Types.RdpVerifyCertificateResult.NotTrusted) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage.Types.RdpVerifyCertificateResult.NotTrusted) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RdpVerifyCertificateResultMessage other) {
      if (other == null) {
        return;
      }
      if (other.Result != global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage.Types.RdpVerifyCertificateResult.NotTrusted) {
        Result = other.Result;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = (global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage.Types.RdpVerifyCertificateResult) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = (global::RdpBridge.Protocol.RdpVerifyCertificateResultMessage.Types.RdpVerifyCertificateResult) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the RdpVerifyCertificateResultMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum RdpVerifyCertificateResult {
        [pbr::OriginalName("NotTrusted")] NotTrusted = 0,
        [pbr::OriginalName("PermenantlyTrusted")] PermenantlyTrusted = 1,
        [pbr::OriginalName("TemporarilyTrusted")] TemporarilyTrusted = 2,
      }

    }
    #endregion

  }

  public sealed partial class RdpSessionEndMessage : pb::IMessage<RdpSessionEndMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RdpSessionEndMessage> _parser = new pb::MessageParser<RdpSessionEndMessage>(() => new RdpSessionEndMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RdpSessionEndMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RdpBridge.Protocol.RdpReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpSessionEndMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpSessionEndMessage(RdpSessionEndMessage other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RdpSessionEndMessage Clone() {
      return new RdpSessionEndMessage(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RdpSessionEndMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RdpSessionEndMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RdpSessionEndMessage other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
